version: '3'
services:
  mongodb:
    image: mongo:latest
    environment:
        MONGO_INITDB_DATABASE: portal-bca
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: bca@2020
    ports:
        - 27017:27017
    volumes:
        - mongodb_data_container:/data/db
    networks:
      - advocacy-network

  data-manager:
    image: local/data-manager:latest
    ports:
      - "3000:3000"
    environment:
        AUTHSERVICE: http://localhost:3001/validaterequest
        SERVICEPORT: 3000
        DBHOST: localhost
        DBPORT: 27017
        DBNAME: portal-bca
        DBUSER: root
        DBPASS: bca@2020
    networks:
      - advocacy-network
    depends_on:
      - mongodb

networks:
  advocacy-network:
    external:
      name: advocacy-network

volumes:
  mongodb_data_container:
    external: true